Privacy Policy
Last updated: April 22, 2026

This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use Drift Legend : Mission Racing (the "Service") and tells You about Your privacy rights and how the law protects You.

1. Interpretation and Definitions
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to the developer of Drift Legend : Mission Racing.

Device means any device that can access the Service such as a computer, a cellphone, or a digital tablet.

Personal Data is any information that relates to an identified or identifiable individual.

Service refers to the Application.

Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a level visit).

2. Collecting and Using Your Personal Data
Types of Data Collected
Personal Data: While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:

Email address (for support and inquiries)

Usage Data: Usage Data is collected automatically when using the Service. This may include:

Your Device's Internet Protocol address (IP address)

Device type, unique device identifiers, and OS version

In-game activity (drift scores, mission progress, car unlocks)

Diagnostic data (crash reports)

3. Third-Party Services
The Application uses third-party services that may collect information used to identify you. We use these services to improve gameplay and provide ads:

Google Play Game Services: For leaderboards and achievements.

AdMob / Unity Ads: For providing personalized or non-personalized advertisements.

Firebase / Unity Analytics: To understand player behavior and optimize game performance.

4. Children's Privacy
Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.

5. Data Security and Retention
The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. We strive to use commercially acceptable means to protect Your Personal Data but cannot guarantee its absolute security.

6. Your Rights (GDPR/CCPA)
Depending on your location, you have the right to:

Access, update, or delete the information we have on you.

Opt-out of data collection for advertising purposes.
To exercise these rights, please contact us at the email provided below.

7. Changes to this Privacy Policy
We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.

8. Contact Us
If you have any questions about this Privacy Policy, You can contact us:

By email: enesyaman04@gmail.com
